name : Actions Workflow

on :
    push:
    repository_dispatch:
        types: [build]

jobs : 
    run-github-actions:
        runs-on : ubuntu-latest
        steps : 
            - name : Js-Action
              id : id0870
              uses : amritsingh0870/hello-world-javascript-action@v1
              with :
                who-to-greet : Amrit
            - name : Log Greeting time
              run : echo "${{ steps.id0870.outputs.time }}"