name : Actions Workflow

on : [push]

jobs : 
    run-github-actions:
        runs-on : ubuntu-latest
        steps : 
            - name : Js-Action
              id : id0870
              uses : ./
              with :
                who-to-greet : Amrit
            - name : Log Greeting time
              run : echo "${{ steps.id0870.outputs.time }}"