name : Shell Commands

on : [push]

jobs :
    run-shell-command : 
        runs-on : ubuntu-latest
        steps :
          - name : echo a string
            run : echo "Hello Amrit"
          - name : multiline script
            run : |
                node -v
                npm -v
          - name : Python Command 
            run : |
                for i in range(6):
                    for j in range(i+1):
                        print(j,end="")
                    print()

            shell : python

